apiVersion: v1
kind: Service
metadata: 
  name: nginx
  labels: 
    name: nginx
spec:
  type: NodePort
  ports:
    - name: http
      port: 80
      # targetPort: 80
  selector: 
    name: nginx
    version: "1.10"
