apiVersion: apps/v1beta2
kind: Deployment
metadata:
 name: ez-deployment
spec:
 selector:
   matchLabels:
     app: ez-nginx-app
 replicas: 1
 template:
   metadata:
     labels:
       app: ez-nginx-app
   spec:
     containers:
     - name: nginx
       image: nginx:1.13.12
       ports:
       - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
 labels:
   app: ez-nginx-app
 name: ez-nginx-svc
 namespace: default
spec:
 type: NodePort
 ports:
   - port: 80
 selector:
   app: ez-nginx-app
