apiVersion: apps/v1
kind: Deployment
metadata:
  name: iis-deploy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: iis
  tolerations:
  - key: "opsys-taint"
    operator: Equals
    value: "windows"
  template:
    metadata:
      labels:
        app: iis
    spec:
      containers:
      - name: iis
        image: microsoft/iis
        resources:
          limits:
            memory: "128Mi"
            cpu: 2
        ports:
        - containerPort: 80
      nodeSelector:
        beta.kubernetes.io/os: windows
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: iis
  name: iis-svc
  namespace: default
spec:
  type: NodePort
  ports:
    - port: 80
  selector:
    app: iis
