apiVersion: v1
kind: Service
metadata:
  name: nginx2
  namespace: windows
  labels:
    app: nginx
spec:
  ports:
  - port: 80
    name: http
  selector:
    app: nginx2 
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: nginx2
  namespace: windows
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: nginx2
    spec:
      containers:
      - name: nginx2
        image: nginx
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 80
---
